version: '3'

services:
  postgres:
    container_name: 'tracker_dev_postgres'
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: 'tracker_dev_redis'
    restart: always
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env

volumes:
  postgres-data:
  redis-data:
