version: '3'

services:
  django:
    container_name: 'tracker_django'
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: 'tracker_postgres'
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: 'tracker_redis'
    restart: always
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    env_file:
      - .env

  nginx:
    container_name: 'tracker_nginx'
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - django

volumes:
  postgres-data:
  redis-data:
  static:
  media:
