version: '3'

services:
  postgres:
    container_name: 'tracker_dev_postgres'
    restart: always
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
