# Generated by Django 5.0.1 on 2024-01-31 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('it', 'in-transit'), ('t', 'transit'), ('is', 'inbounded-scan'), ('s', 'scanned'), ('id', 'in-delivery'), ('d', 'delivery')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_article', to='article.article')),
                ('carrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_carrier', to='dashboard.carrier')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_receiver', to='dashboard.receiver')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_sender', to='dashboard.sender')),
            ],
        ),
    ]
